{ config, lib, ... }:
let
  cfg = config.apps.obsidian;
in
{
  options.apps.obsidian = {
    enable = lib.mkEnableOption "Obsidian with a declaratively deployed plugin set";

    vault = lib.mkOption {
      type = lib.types.str;
      default = "/home/otis/Documents/uni";
      description = ''
        Absolute path of the vault this module deploys plugins into.

        The vault itself is *not* part of this repo: it is its own git
        repository, committed by the obsidian-git plugin, because it is course
        notes (user data) and not system configuration. This module only owns
        the `.obsidian/` machinery inside it.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.extraOptions =
      { pkgs, lib, ... }:
      let
        plugins = import ./_lib/plugins.nix { inherit pkgs lib; };

        # Same theme lookup as modules/desktop/dms/theme.nix and
        # modules/apps/anki: the active theme's `obsidian` table drives the
        # CSS snippet below, so no colour is written here.
        theme = (import ../../../themes { inherit lib; }).get config.theming.stylix.theme;
        ob = theme.obsidian;

        # A slot is a `palette` name, or a literal hex for a one-off.
        swatch = name: theme.palette.${name} or name;

        # Obsidian wants callout accents as a bare "r, g, b" triplet, and Nix
        # has no hex parser, so spell one out.
        hexDigits = lib.listToAttrs (
          lib.imap0 (i: c: lib.nameValuePair c i) (lib.stringToCharacters "0123456789abcdef")
        );
        byteAt =
          h: i:
          hexDigits.${lib.toLower (builtins.substring i 1 h)} * 16
          + hexDigits.${lib.toLower (builtins.substring (i + 1) 1 h)};
        rgb =
          name:
          let
            h = lib.removePrefix "#" (swatch name);
          in
          "${toString (byteAt h 0)}, ${toString (byteAt h 2)}, ${toString (byteAt h 4)}";

        headingVars = lib.concatStringsSep "\n" (
          lib.imap1 (i: c: "  --h${toString i}-color: ${swatch c};") ob.headings
        );

        # Two selectors per entry on purpose. Obsidian's own callouts key off
        # data-callout; math-booster re-renders its environments as
        # `.theorem-callout-<env>` and drops that attribute, so a rule written
        # only the first way colours the warning boxes and leaves every
        # theorem grey. The env names are math-booster's own
        # (THEOREM_LIKE_ENV_IDs in its main.js). !important because that
        # plugin pins --callout-color to --text-normal from a `:has()` rule no
        # snippet selector can outrank.
        calloutRules = lib.concatStringsSep "\n" (
          lib.mapAttrsToList
            (name: colour: ''
              .callout[data-callout="${name}"],
              .theorem-callout.theorem-callout-${name} { --callout-color: ${rgb colour} !important; }'')
            ob.callouts
        );

        # Regenerated on every activation (never seeded): this file is
        # entirely derived from the theme, so a stale copy would silently
        # outlive a theme switch. Everything the user might reasonably want to
        # change by hand belongs in a *second* snippet of their own.
        themeCss = pkgs.writeText "sitolamix-obsidian.css" ''
          /* Generated by modules/apps/obsidian from themes/${config.theming.stylix.theme}.nix.
             Do not edit: every rebuild overwrites this file. Add a second
             snippet next to it for personal tweaks. */
          .theme-dark,
          .theme-light {
            --font-text-theme: ${config.stylix.fonts.serif.name};
            --font-interface-theme: ${config.stylix.fonts.sansSerif.name};
            --font-monospace-theme: ${config.stylix.fonts.monospace.name};

            --background-primary: ${swatch ob.background};
            --background-primary-alt: ${swatch ob.backgroundAlt};
            --background-secondary: ${swatch ob.sidebar};
            --background-secondary-alt: ${swatch ob.sidebarAlt};
            --background-modifier-border: ${swatch ob.border};
            --background-modifier-border-hover: ${swatch ob.active};
            --background-modifier-border-focus: ${swatch ob.accent};
            --background-modifier-hover: ${swatch ob.hover};
            --background-modifier-active-hover: ${swatch ob.active};
            --background-modifier-form-field: ${swatch ob.backgroundAlt};
            --background-modifier-error: ${swatch ob.error};
            --background-modifier-success: ${swatch ob.success};

            --text-normal: ${swatch ob.text};
            --text-muted: ${swatch ob.textMuted};
            --text-faint: ${swatch ob.textFaint};
            --text-on-accent: ${swatch ob.textOnAccent};
            --text-error: ${swatch ob.error};
            --text-success: ${swatch ob.success};
            --text-accent: ${swatch ob.accent};
            --text-accent-hover: ${swatch ob.linkHover};
            --text-selection: ${swatch ob.selection};
            --text-highlight-bg: ${swatch ob.selection};

            --link-color: ${swatch ob.link};
            --link-color-hover: ${swatch ob.linkHover};
            --link-unresolved-color: ${swatch ob.linkUnresolved};
            --link-external-color: ${swatch ob.link};

            --interactive-normal: ${swatch ob.backgroundAlt};
            --interactive-hover: ${swatch ob.hover};
            --interactive-accent: ${swatch ob.accent};
            --interactive-accent-hover: ${swatch ob.linkHover};

            --divider-color: ${swatch ob.border};
            --titlebar-background: ${swatch ob.sidebar};
            --titlebar-background-focused: ${swatch ob.sidebar};
            --tab-text-color-focused-active: ${swatch ob.accent};

            --code-background: ${swatch ob.codeBackground};
            --code-normal: ${swatch ob.code};
            --code-comment: ${swatch ob.textFaint};

            --tag-color: ${swatch ob.tag};
            --tag-background: ${swatch ob.backgroundAlt};

            --blockquote-border-color: ${swatch ob.accent};
            --table-header-background: ${swatch ob.backgroundAlt};
            --table-row-alt-background: ${swatch ob.backgroundAlt};

            --checkbox-color: ${swatch ob.accent};
            --checkbox-color-hover: ${swatch ob.linkHover};
            --checkbox-marker-color: ${swatch ob.textOnAccent};

            --scrollbar-bg: ${swatch ob.background};
            --scrollbar-thumb-bg: ${swatch ob.border};
            --scrollbar-active-thumb-bg: ${swatch ob.active};

          ${headingVars}
          }

          /* math-booster also hard-sets the font to "CMU Serif, Times" from
             the same unbeatable rule. Take it back, so the whole vault stays
             on one typeface -- the one stylix chose. */
          .theorem-callout {
            font-family: var(--font-text) !important;
            /* Its "Framed" style draws `border: solid var(--border-width)`
               with no colour, so the frame falls back to the text colour and
               every environment ends up the same grey. Paint it from the
               environment's own accent instead, and tint the label to match:
               that accent is the only thing distinguishing a definition from
               a theorem at a glance. */
            border-color: rgba(var(--callout-color), 0.5) !important;
          }

          .theorem-callout .theorem-callout-main-title {
            color: rgb(var(--callout-color));
          }

          /* MathJax inherits colour from the text around it, which is what you
             want inside a callout: a formula in a theorem should not be the
             one black thing on a blue card. */
          .math { color: inherit; }

          ${calloutRules}
        '';
        # Written once, then left to Obsidian. Every file under .obsidian/ is
        # rewritten by the app the moment a setting is toggled, so seeding is
        # the only honest option: a file this module rewrote on every
        # activation would silently undo changes made in the app's own
        # settings UI. Change a *plugin version* here; change a *setting* in
        # Obsidian.
        seeds = {
          "core-plugins.json" = builtins.toJSON {
            "file-explorer" = true;
            "global-search" = true;
            "switcher" = true;
            "graph" = true;
            "backlink" = true;
            "outgoing-link" = true;
            "tag-pane" = true;
            "outline" = true;
            "templates" = true;
            "daily-notes" = true;
            "command-palette" = true;
            "editor-status" = true;
            "bookmarks" = true;
            "properties" = true;
          };

          "app.json" = builtins.toJSON {
            # Lectures are typed, not clicked: live preview renders the maths
            # while the LaTeX source stays editable under the cursor.
            livePreview = true;
            # New note from an unresolved [[link]] lands next to its source
            # instead of in the vault root.
            newFileLocation = "current";
            attachmentFolderPath = "04 Excalidraw";
            alwaysUpdateLinks = true;
            useMarkdownLinks = false;
            showLineNumber = false;
            # Every note already opens with its own `# Titel` heading, and
            # Obsidian renders the filename above that — two identical titles
            # on every page without this.
            showInlineTitle = false;
            # Obsidian's own spellchecker has no Dutch dictionary on Linux
            # without extra system hunspell wiring; red squiggles under every
            # Dutch word are worse than none.
            spellcheck = false;
          };

          "templates.json" = builtins.toJSON {
            folder = "99 Meta/Templates";
            dateFormat = "YYYY-MM-DD";
          };

          "daily-notes.json" = builtins.toJSON {
            folder = "00 Dagelijks";
            format = "YYYY-MM-DD";
            template = "99 Meta/Templates/Dag.md";
          };
        };

        seedScript = lib.concatStringsSep "\n" (
          lib.mapAttrsToList (name: json: ''
            if [ ! -e "$cfgdir/${name}" ]; then
              printf '%s' ${lib.escapeShellArg json} > "$cfgdir/${name}"
            fi
          '') seeds
        );

        # Plugin *code* is redeployed every activation (that is the point of
        # pinning it in Nix); each plugin's data.json — its settings — is
        # never touched, so anything configured in the app survives a rebuild.
        # A plugin dropped from ./_lib/plugins.nix would otherwise stay on disk
        # and keep running forever. Only directories carrying the marker this
        # module writes are removed, so plugins installed by hand from
        # Obsidian's own browser are never touched.
        pruneScript = ''
          for dir in "$plugdir"/*/; do
            id=$(basename "$dir")
            if [ -e "$dir/.nix-managed" ] && ! printf '%s\n' ${
              lib.concatMapStringsSep " " (p: lib.escapeShellArg p.id) plugins
            } | grep -qx "$id"; then
              rm -rf "$dir"
              if [ -e "$cfgdir/community-plugins.json" ]; then
                ${pkgs.jq}/bin/jq --arg id "$id" 'map(select(. != $id))' \
                  "$cfgdir/community-plugins.json" > "$cfgdir/community-plugins.json.tmp"
                mv "$cfgdir/community-plugins.json.tmp" "$cfgdir/community-plugins.json"
              fi
            fi
          done
        '';

        # Plugin code on disk is inert until its id is listed here, so this
        # one file cannot be seed-once like the rest: a plugin added to
        # ./_lib/plugins.nix months from now would land on disk and never
        # switch on. Union rather than overwrite, so ids Obsidian added for
        # plugins installed from its own browser survive. Consequence: a
        # plugin listed here cannot be turned off in the app, only by removing
        # it from ./_lib/plugins.nix.
        enableScript = ''
          ids=${lib.escapeShellArg (builtins.toJSON (map (p: p.id) plugins))}
          if [ -e "$cfgdir/community-plugins.json" ]; then
            ${pkgs.jq}/bin/jq -n --argjson a "$(cat "$cfgdir/community-plugins.json")" \
              --argjson b "$ids" '$a + $b | unique' > "$cfgdir/community-plugins.json.tmp"
            mv "$cfgdir/community-plugins.json.tmp" "$cfgdir/community-plugins.json"
          else
            printf '%s' "$ids" > "$cfgdir/community-plugins.json"
          fi
        '';

        deployScript = lib.concatMapStringsSep "\n" (p: ''
          install -d "$plugdir/${p.id}"
          ${lib.concatMapStringsSep "\n" (
            file: ''install -m644 "${p.files.${file}}" "$plugdir/${p.id}/${file}"''
          ) (lib.attrNames p.files)}
          touch "$plugdir/${p.id}/.nix-managed"
        '') plugins;
        # The snippet is inert until Obsidian is told to load it, and the base
        # theme has to match the palette's polarity or half the vault renders
        # on a white page. Merged rather than written whole: appearance.json
        # also holds zoom, font sizes and the user's own snippet list.
        appearanceScript = ''
          appearance="$cfgdir/appearance.json"
          [ -e "$appearance" ] || printf '%s' '{}' > "$appearance"
          ${pkgs.jq}/bin/jq \
            --arg theme ${lib.escapeShellArg (if theme.polarity == "dark" then "obsidian" else "moonstone")} \
            --arg accent ${lib.escapeShellArg (swatch ob.accent)} \
            '.theme = $theme
             | .accentColor = $accent
             | .enabledCssSnippets = ((.enabledCssSnippets // []) + ["sitolamix"] | unique)' \
            "$appearance" > "$appearance.tmp"
          mv "$appearance.tmp" "$appearance"
        '';

      in
      {
        home = {
          packages = [ pkgs.obsidian ];

          # Obsidian ships its own updater: it downloads a newer app.asar into
          # ~/.config/obsidian and runs that instead of the one in the Nix
          # store, so `pkgs.obsidian` stops describing what actually runs (seen
          # here as "Version 1.13.7 / Installer version 1.13.4"). The app's own
          # setting for this writes `updateDisabled` into obsidian.json, so set
          # that key -- merged, never rewritten, because the same file holds the
          # vault registry.
          activation.obsidianNoSelfUpdate = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
            conf="$HOME/.config/obsidian/obsidian.json"
            install -d "$HOME/.config/obsidian"
            if [ -e "$conf" ]; then
              ${pkgs.jq}/bin/jq '.updateDisabled = true' "$conf" > "$conf.tmp"
              mv "$conf.tmp" "$conf"
            else
              printf '%s' '{"updateDisabled":true}' > "$conf"
            fi
          '';

          activation.obsidianPlugins = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
            cfgdir=${lib.escapeShellArg "${cfg.vault}/.obsidian"}
            plugdir=${lib.escapeShellArg "${cfg.vault}/.obsidian/plugins"}
            install -d "$plugdir"
            ${deployScript}
            ${pruneScript}
            ${seedScript}
            ${enableScript}
            install -d "$cfgdir/snippets"
            install -m644 "${themeCss}" "$cfgdir/snippets/sitolamix.css"
            ${appearanceScript}
          '';
        };
      };
  };
}
